(defparameter *field* (make-hash-table))
(defparameter *food* (make-hash-table))
(defparameter *seeds* (make-hash-table))
(setf (gethash 0 *seeds*) 0)
(setf (gethash 0 *food*) 0)
(defparameter *seedchance* (random 11))
(defparameter *grow0* 0)
(defparameter *grow1* 0)
(defparameter *grow2* 0)
(defparameter *grow3* 0)
(defparameter *grow4* 0)
(defparameter *grow5* 0)
(defparameter *grow6* 0)
(defparameter *grow7* 0)
(defparameter *grow8* 0)
(defparameter *grow9* 0)

(defun tend ()
    (if (or (eq (gethash 0 *field*) '|___|||) (eq (gethash 0 *field*) '_Y_) (eq (gethash 0 *field*) '_t_)) (error "You have already made your field! Type \":q\" to return to the game~%"))
    (princ "Tending")
    (dotimes (i 10) (progn
        (princ ".") 
        (sleep 0.5)
        (setf (gethash i *field*) '|___|||))))
        
(defun showcrops ()
    (format t "~%~A ~A ~A ~A ~A~%~A ~A ~A ~A ~A~%" (gethash 0 *field*) (gethash 1 *field*) (gethash 2 *field*) (gethash 3 *field*) (gethash 4 *field*) (gethash 5 *field*) (gethash 6 *field*) (gethash 7 *field*) (gethash 8 *field*) (gethash 9 *field*)))

(defun plant (x)
    (if (> (gethash 0 *seeds*) 0)
      (cond ((eq x 1) (progn (setf (gethash 0 *field*) '_t_) (setq *grow0* 0)))
      ((eq x 2) (progn (setf (gethash 1 *field*) '_t_) (setq *grow1* 0)))
      ((eq x 3) (progn (setf (gethash 2 *field*) '_t_) (setq *grow2* 0)))
      ((eq x 4) (progn (setf (gethash 3 *field*) '_t_) (setq *grow3* 0)))
      ((eq x 5) (progn (setf (gethash 4 *field*) '_t_) (setq *grow4* 0)))
      ((eq x 6) (progn (setf (gethash 5 *field*) '_t_) (setq *grow5* 0)))
      ((eq x 7) (progn (setf (gethash 6 *field*) '_t_) (setq *grow6* 0)))
      ((eq x 8) (progn (setf (gethash 7 *field*) '_t_) (setq *grow7* 0)))
      ((eq x 9) (progn (setf (gethash 8 *field*) '_t_) (setq *grow8* 0)))
      ((eq x 10) (progn (setf (gethash 9 *field*) '_t_) (setq *grow9* 0))))
      (format t "~%You do not have any seeds!~%")))

(defun harvest (x)
    (setq *seedchance* (random 11))
    (if (eq *seedchance* 7) (progn (format t "You found some seeds while harvesting the crops!")))
    (cond ((and (eq x 1) (eq (gethash 0 *field*) '_Y_)) (progn (setf (gethash 0 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 2) (eq (gethash 1 *field*) '_Y_)) (progn (setf (gethash 1 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 3) (eq (gethash 2 *field*) '_Y_)) (progn (setf (gethash 2 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 4) (eq (gethash 3 *field*) '_Y_)) (progn (setf (gethash 3 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 5) (eq (gethash 4 *field*) '_Y_)) (progn (setf (gethash 4 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 6) (eq (gethash 5 *field*) '_Y_)) (progn (setf (gethash 5 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 7) (eq (gethash 6 *field*) '_Y_)) (progn (setf (gethash 6 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 8) (eq (gethash 7 *field*) '_Y_)) (progn (setf (gethash 7 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 9) (eq (gethash 8 *field*) '_Y_)) (progn (setf (gethash 8 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((and (eq x 10) (eq (gethash 9 *field*) '_Y_)) (progn (setf (gethash 9 *field*) '|___|||) (format t "~%You got +1 Corn!~%") (incf (gethash 0 *food*) 1)))
    ((eq (gethash x *field*) '|___|||) (format t "There is no crop to harvest!~%")))
    (cond ((and (eq x 1) (eq (gethash 0 *field*) '_t_)) (progn (setf (gethash 0 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 2) (eq (gethash 1 *field*) '_t_)) (progn (setf (gethash 1 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 3) (eq (gethash 2 *field*) '_t_)) (progn (setf (gethash 2 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 4) (eq (gethash 3 *field*) '_t_)) (progn (setf (gethash 3 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 5) (eq (gethash 4 *field*) '_t_)) (progn (setf (gethash 4 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 6) (eq (gethash 5 *field*) '_t_)) (progn (setf (gethash 5 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 7) (eq (gethash 6 *field*) '_t_)) (progn (setf (gethash 6 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 8) (eq (gethash 7 *field*) '_t_)) (progn (setf (gethash 7 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 9) (eq (gethash 8 *field*) '_t_)) (progn (setf (gethash 8 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))
    ((and (eq x 10) (eq (gethash 9 *field*) '_t_)) (progn (setf (gethash 9 *field*) '|___|||) (format t "~%You harvested the crop too early!~%")))))

(defun water ()
    (when (eq (gethash 0 *field*) '_t_) (setq *grow0* (+ *grow0* 10)))
    (when (eq (gethash 1 *field*) '_t_) (setq *grow1* (+ *grow1* 10)))
    (when (eq (gethash 2 *field*) '_t_) (setq *grow2* (+ *grow2* 10)))
    (when (eq (gethash 3 *field*) '_t_) (setq *grow3* (+ *grow3* 10)))
    (when (eq (gethash 4 *field*) '_t_) (setq *grow4* (+ *grow4* 10)))
    (when (eq (gethash 5 *field*) '_t_) (setq *grow5* (+ *grow5* 10)))
    (when (eq (gethash 6 *field*) '_t_) (setq *grow6* (+ *grow6* 10)))
    (when (eq (gethash 7 *field*) '_t_) (setq *grow7* (+ *grow7* 10)))
    (when (eq (gethash 8 *field*) '_t_) (setq *grow8* (+ *grow8* 10)))
    (when (eq (gethash 9 *field*) '_t_) (setq *grow9* (+ *grow9* 10)))
    (when (and (eq *grow0* 100) (eq (gethash 0 *field*) '_t_)) (progn (format t "~%The crop in plot 1 is ready to harvest!~%") (setf (gethash 0 *field*) '_Y_) (setq *grow0* 0)))
    (when (and (eq *grow1* 100) (eq (gethash 1 *field*) '_t_)) (progn (format t "~%The crop in plot 2 is ready to harvest!~%") (setf (gethash 1 *field*) '_Y_) (setq *grow1* 0)))
    (when (and (eq *grow2* 100) (eq (gethash 2 *field*) '_t_)) (progn (format t "~%The crop in plot 3 is ready to harvest!~%") (setf (gethash 2 *field*) '_Y_) (setq *grow2* 0)))
    (when (and (eq *grow3* 100) (eq (gethash 3 *field*) '_t_)) (progn (format t "~%The crop in plot 4 is ready to harvest!~%") (setf (gethash 3 *field*) '_Y_) (setq *grow3* 0)))
    (when (and (eq *grow4* 100) (eq (gethash 4 *field*) '_t_)) (progn (format t "~%The crop in plot 5 is ready to harvest!~%") (setf (gethash 4 *field*) '_Y_) (setq *grow4* 0)))
    (when (and (eq *grow5* 100) (eq (gethash 5 *field*) '_t_)) (progn (format t "~%The crop in plot 6 is ready to harvest!~%") (setf (gethash 5 *field*) '_Y_) (setq *grow5* 0)))
    (when (and (eq *grow6* 100) (eq (gethash 6 *field*) '_t_)) (progn (format t "~%The crop in plot 7 is ready to harvest!~%") (setf (gethash 6 *field*) '_Y_) (setq *grow6* 0))) 
    (when (and (eq *grow7* 100) (eq (gethash 7 *field*) '_t_)) (progn (format t "~%The crop in plot 8 is ready to harvest!~%") (setf (gethash 7 *field*) '_Y_) (setq *grow7* 0)))
    (when (and (eq *grow8* 100) (eq (gethash 8 *field*) '_t_)) (progn (format t "~%The crop in plot 9 is ready to harvest!~%") (setf (gethash 8 *field*) '_Y_) (setq *grow8* 0)))
    (when (and (eq *grow9* 100) (eq (gethash 9 *field*) '_t_)) (progn (format t "~%The crop in plot 10 is ready to harvest!~%") (setf (gethash 9 *field*) '_Y_) (setq *grow9* 0))))
