(defun berryflag ()
  (format t "~%You ate a berry. +10 HP -2 berries~%") (popberries) (+ *health* 10))
(defun axeflag ()
  (format t "~%You made an axe!~%") (pushaxe) (popwood) (popwood) (popminerals))
(defun spearflag ()
  (format t "~%You made a spear!~%") (pushspear))
(defun pickflag ()
  (format t "~%You made a pickaxe!~%") (pushpick))
(defun cookflag ()
  (format t "~%You cooked the crab meat! ~%") (pushcooked) (popraw))
(defun eatcrabflag ()
  (popcooked) (+ *health* 20) (format t "~%You ate the crab. +20 HP -2 cooked Crab meat ~%~%"))
(defun showinv ()
  (format t "~%Total Raw meat: ~A ~%Total Cooked Meat: ~A ~%Berries: ~A ~%Wood: ~A ~%Minerals: ~A ~%Corn: ~A~%Flax: ~A ~%Cloth: ~A ~%Medkit: ~A ~%Corn Seeds: ~A~%~%" (+ (gethash 0 *meat*) (gethash 0 *fish*)) (+ (gethash 0 *cookedfish*) (gethash 0 *cookedmeat*)) (gethash 0 *berries*) (gethash 0 *wood*) (gethash 0 *minerals*) (gethash 0 *food*) (gethash 0 *flax*) (gethash 0 *cloth*) (gethash 0 *medkit*) (gethash 0 *seeds*))
  (when (eq *inventory* 0) (tut2)))
(defun flaxflag ()
  (format t "~%You found some flax!~%") (pushflax))
(defun clothflag ()
  (format t "~%You sewed some cloth!~%") (pushcloth))
(defun houseflag ()
  (format t "~%~%~%~%You made yourself a house!~%You Win!~%~%~%~%") (quit))

