(defun pushberries ()
  (incf (gethash 0 *berries*) 2) (format t "~%+2 berries ~%~%"))
(defun popberries ()
  (decf (gethash 0 *berries*) 2))
(defun pushraw ()
  (incf (gethash 0 *meat*) 2) (format t "~%+2 Raw Crabs ~%~%"))
(defun popraw ()
  (decf (gethash 0 *meat*) 2))
(defun pushcooked ()
  (incf (gethash 0 *cookedmeat*) 2) (format t "~%+2 Cooked Crabs ~%~%"))
(defun popcooked ()
  (decf (gethash 0 *cooked*meat*) 2))
(defun pushaxe ()
  (setf (gethash 0 *tools*) t) (format t "~%+1 axe ~%~%"))
(defun pushpick ()
  (setf (gethash 1 *tools*) t) (format t "~%+1 pickaxe ~%~%"))
(defun pushspear ()
  (setf (gethash 2 *tools*) t) (format t "~%+1 spear ~%~%"))
(defun pushwood ()
  (incf (gethash 0 *wood*) 2) (format t "~%+2 wood ~%~%"))
(defun popwood ()
  (decf (gethash 0 *wood*) 2))
(defun pushminerals ()
  (incf (gethash 0 *minerals*) 2) (format t "~%+2 minerals ~%~%"))
(defun popminerals ()
  (decf (gethash 0 *minerals*) 2))
(defun pushfish ()
  (incf (gethash 0 *fish* ) 2) (format t "~%+2 raw fish ~%~%"))
(defun popfish ()
  (decf (gethash 0 *fish*) 2))
(defun pushcookedfish ()
  (incf (gethash 0 *cookedfish*) 2) (format t "~%+2 cooked fish ~%~%"))
(defun pushflax ()
  (incf (gethash 0 *flax*) 2) (format t "~%+2 flax ~%~%"))
(defun popflax ()
  (decf (gethash 0 *flax*) 2))
(defun pushcloth ()
  (decf (gethash 0 *flax*) 2) (incf (gethash 0 *cloth*) 2) (format t "~%-2 flax +2 cloth ~%~%"))
(defun popcloth ()
  (decf (gethash 0 *flax*) 2))
(defun pushseeds ()
  (incf (gethash 0 *seeds*) 2) (format t "~%+2 seeds~%"))